// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnswerController from "./answer_controller.js"
application.register("answer", AnswerController)

import DeskController from "./desk_controller.js"
application.register("desk", DeskController)

import GamestartController from "./gamestart_controller.js"
application.register("gamestart", GamestartController)

import GeneriqueController from "./generique_controller.js"
application.register("generique", GeneriqueController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import JsConfettiController from "./js_confetti_controller.js"
application.register("js-confetti", JsConfettiController)

import ListenerController from "./listener_controller.js"
application.register("listener", ListenerController)

import SolutionController from "./solution_controller.js"
application.register("solution", SolutionController)

import TimerController from "./timer_controller.js"
application.register("timer", TimerController)
