development:
  adapter: redis
  channel_prefix: RPUW_developement

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: RPUW_production
